# 2.1.10 Practical Activites: 
## 2.1.10 & 2.2.8
## Importing Data and Handling Missing Values

In [1]:
import pandas as pd

In [2]:
movies = pd.read_excel('movies.xlsx')
ott = pd.read_csv('ott.csv')

In [3]:
movies

,Title,Year,Age,IMDb,Rotten Tomatoes,Directors,Genres,Country,Language,Runtime
0,Inception,2010,13+,8.8,0.87,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,The Matrix,1999,18+,8.7,0.87,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,Avengers: Infinity War,2018,13+,8.5,0.84,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,Back to the Future,1985,7+,8.5,0.96,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,"The Good, the Bad and the Ugly",1966,18+,8.8,0.97,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0
5,Spider-Man: Into the Spider-Verse,2018,7+,8.4,0.97,"Bob Persichetti,Peter Ramsey,Rodney Rothman","Animation,Action,Adventure,Family,Sci-Fi",United States,"English,Spanish",117.0
6,The Pianist,2002,18+,8.5,0.95,Roman Polanski,"Biography,Drama,Music,War","United Kingdom,France,Poland,Germany","English,German,Russian",150.0
7,Django Unchained,2012,18+,8.4,0.87,Quentin Tarantino,"Drama,Western",United States,"English,German,French,Italian",165.0
8,Raiders of the Lost Ark,1981,7+,8.4,0.95,Steven Spielberg,"Action,Adventure",United States,"English,German,Hebrew,Spanish,Arabic,Nepali",115.0
9,Inglourious Basterds,2009,18+,8.3,0.89,Quentin Tarantino,"Adventure,Drama,War","Germany,United States","English,German,French,Italian",153.0
10,Taxi Driver,1976,18+,8.3,0.95,Martin Scorsese,"Crime,Drama",United States,"English,Spanish",114.0
11,3 Idiots,2009,13+,8.4,1.00,Rajkumar Hirani,"Comedy,Drama",India,"Hindi,English",170.0
12,Pan's Labyrinth,2006,18+,8.2,0.95,Guillermo del Toro,"Drama,Fantasy,War","Mexico,Spain",Spanish,118.0
13,Room,2015,18+,8.1,0.93,Lenny Abrahamson,"Drama,Thriller","Ireland,Canada,United Kingdom,United States",English,118.0
14,Monty Python and the Holy Grail,1975,7+,8.2,0.97,"Terry Gilliam,Terry Jones","Adventure,Comedy,Fantasy",United Kingdom,"English,French,Latin",91.0
15,Once Upon a Time in the West,1968,13+,8.5,0.95,Sergio Leone,Western,"Italy,United States","Italian,English,Spanish",165.0
16,Indiana Jones and the Last Crusade,1989,13+,8.2,0.88,Steven Spielberg,"Action,Adventure",United States,"English,German,Greek,Arabic",127.0
17,Groundhog Day,1993,7+,8.0,0.96,Harold Ramis,"Comedy,Fantasy,Romance",United States,"English,French,Italian",101.0
18,The King's Speech,2010,18+,8.0,0.95,Tom Hooper,"Biography,Drama,History","United Kingdom,United States,Australia",English,118.0
19,Her,2013,18+,8.0,0.95,Spike Jonze,"Drama,Romance,Sci-Fi",United States,English,126.0
20,There Will Be Blood,2007,18+,8.2,0.91,Paul Thomas Anderson,Drama,United States,"English,American Sign Language",158.0
21,The Social Network,2010,13+,7.7,0.96,David Fincher,"Biography,Drama",United States,"English,French",120.0
22,Dallas Buyers Club,2013,18+,8.0,0.93,Jean-Marc Vallée,"Biography,Drama",United States,"English,Japanese",117.0
23,The Perks of Being a Wallflower,2012,13+,8.0,0.86,Stephen Chbosky,"Drama,Romance",United States,English,103.0
24,Life of Brian,1979,18+,8.1,0.95,Terry Jones,Comedy,United Kingdom,"English,Latin",94.0
25,Ex Machina,2015,18+,7.7,0.92,Alex Garland,"Drama,Mystery,Sci-Fi,Thriller","United Kingdom,United States",English,108.0
26,Silver Linings Playbook,2012,18+,7.7,0.92,David O. Russell,"Comedy,Drama,Romance",United States,English,122.0
27,District 9,2009,18+,7.9,0.90,Neill Blomkamp,"Action,Sci-Fi,Thriller","South Africa,United States,New Zealand,Canada","English,Nyanja,Afrikaans,Zulu,Xhosa,Southern S...",112.0
28,The Irishman,2019,18+,7.9,0.96,Martin Scorsese,"Biography,Crime,Drama",United States,"English,Italian,Latin,Spanish,German",209.0
29,Moon,2009,18+,7.9,0.90,Duncan Jones,"Drama,Mystery,Sci-Fi","United Kingdom,United States","English,Spanish",97.0
...,...,...,...,...,...,...,...,...,...,...
16714,Drain The Ocean: WWII,2016,7+,7.0,NaN,Mike Slee,History,United States,English,44.0
16715,Hounded,2001,all,5.1,NaN,Neal Israel,"Comedy,Drama,Family",United States,English,91.0
16716,Yellowstone Cubs,1963,all,6.9,NaN,Charles L. Draper,Family,United States,English,48.0
16717,Kingdom of the Blue Whale,2009,NaN,7.3,NaN,NaN,Documentary,United States,English,94.0
16718,Viking Warrior Women,2019,NaN,6.6,NaN,"David Bartlett,Sebastian Peiter","Documentary,Drama,History",United Kingdom,"English,Swedish,German",51.0
16719,Pocahontas,1995,NaN,5.3,0.55,"Mike Gabriel,Eric Goldberg","Animation,Adventure,Drama,Family,Musical,Romance",United States,"English,Algonquin",81.0
16720,Drain Alcatraz,2017,NaN,5.9,NaN,Wayne Abbott,Documentary,United States,English,47.0
16721,The Spaceman and King Arthur,1979,all,5.3,NaN,Russ Mayberry,"Comedy,Family,Adventure,Fantasy,Sci-Fi",United States,English,93.0
16722,Secrets of Life,1956,all,7.2,NaN,James Algar,"Documentary,Family",United States,English,70.0
16723,Hacksaw,1971,7+,6.3,NaN,Larry Lansburgh,Family,United States,English,89.0
16724,Can of Worms,1999,7+,5.0,NaN,Paul Schneider,"Comedy,Family,Sci-Fi","United States,Canada",English,90.0
16725,My Dog the Thief,1969,NaN,6.1,NaN,Robert Stevenson,"Adventure,Drama,Family",United States,English,88.0
16726,Richie Rich's Christmas Wish,1998,all,4.1,NaN,John Murlowski,"Comedy,Family",United States,English,84.0
16727,The Jungle Book: Mowgli's Story,1998,all,4.2,NaN,Nick Marck,"Adventure,Family",United States,English,77.0
16728,How Dogs Got Their Shapes,2016,NaN,6.7,NaN,Keith Haskel,Documentary,United States,English,NaN
16729,Drain The Sunken Pirate City,2017,NaN,6.6,NaN,Sophie Elwin-Harris,Documentary,United Kingdom,English,47.0
16730,Bizarre Dinosaurs,2010,NaN,6.8,NaN,Jenny Kubo,Documentary,United States,English,48.0
16731,Earth Live,2017,NaN,5.5,NaN,Glenn Weiss,Documentary,United States,English,NaN
16732,The Boy Who Talked to Badgers,1975,NaN,6.2,NaN,Gary Nelson,"Adventure,Family",United States,English,89.0
16733,Sea of Hope: America's Underwater Treasures,2017,NaN,7.3,NaN,Robert Nixon,Documentary,United States,English,48.0
16734,Sultan And The Rock Star,1980,NaN,5.9,NaN,Edward M. Abroms,"Adventure,Drama,Family",United States,English,60.0
16735,Secrets of the King Cobra,2010,NaN,6.4,NaN,NaN,Documentary,India,English,NaN
16736,Winged Seduction: Birds of Paradise,2012,NaN,6.5,NaN,Molly Hermann,Documentary,United States,English,NaN
16737,The Bears and I,1974,all,6.2,NaN,Bernard McEveety,"Drama,Family",United States,English,89.0
16738,Whispers: An Elephant's Tale,2000,all,5.0,NaN,Dereck Joubert,"Adventure,Family",United States,English,72.0
16739,The Ghosts of Buxley Hall,1980,NaN,6.2,NaN,Bruce Bilson,"Comedy,Family,Fantasy,Horror",United States,English,120.0
16740,The Poof Point,2001,7+,4.7,NaN,Neal Israel,"Comedy,Family,Sci-Fi",United States,English,90.0
16741,Sharks of Lost Island,2013,NaN,5.7,NaN,Neil Gelinas,Documentary,United States,English,NaN
16742,Man Among Cheetahs,2017,NaN,6.6,NaN,Richard Slater-Jones,Documentary,United States,English,NaN
16743,In Beaver Valley,1950,NaN,NaN,NaN,James Algar,"Documentary,Short,Family",United States,English,32.0

In [4]:
ott

          ID  Netflix  Hulu  Prime Video  Disney+
0          1        0     0            1        0
1          2        0     1            0        0
2          3        0     0            1        0
3          4        1     0            0        0
4          5        0     0            1        0
5          6        0     0            1        0
6          7        1     0            0        0
7          8        0     0            1        0
8          9        0     0            1        0
9         10        1     0            0        0
10        11        1     0            0        0
11        12        0     0            1        0
12        13        1     0            0        0
13        14        1     0            0        0
14        15        0     0            1        0
15        16        1     0            1        0
16        17        1     0            0        0
17        18        0     0            1        0
18        19        0     0            1        0
19        20        1     0            0        0
20        21        0     0            1        0
21        22        1     0            0        0
22        23        1     0            0        0
23        24        0     0            1        0
24        25        0     0            1        0
25        26        0     0            1        0
26        27        1     0            0        0
27        28        1     0            0        0
28        29        0     0            1        0
29        30        0     0            1        0
...      ...      ...   ...          ...      ...
16714  16715        0     0            1        0
16715  16716        1     0            0        0
16716  16717        0     0            1        0
16717  16718        0     0            1        0
16718  16719        0     0            1        0
16719  16720        0     0            1        0
16720  16721        0     0            1        0
16721  16722        0     0            1        0
16722  16723        0     0            1        0
16723  16724        0     0            1        0
16724  16725        0     0            1        0
16725  16726        0     0            1        0
16726  16727        0     0            1        0
16727  16728        0     0            1        0
16728  16729        0     0            1        0
16729  16730        0     0            1        0
16730  16731        0     0            1        0
16731  16732        0     1            1        0
16732  16733        0     0            1        0
16733  16734        0     0            1        0
16734  16735        1     0            0        0
16735  16736        0     0            1        0
16736  16737        0     0            0        1
16737  16738        0     0            1        0
16738  16739        1     0            1        0
16739  16740        0     0            1        0
16740  16741        0     0            1        0
16741  16742        0     0            1        0
16742  16743        0     0            1        0
16743  16744        1     0            0        0

[16744 rows x 5 columns]

In [5]:
print(ott.shape)
print(ott.dtypes)

(16744, 5)
ID             int64
Netflix        int64
Hulu           int64
Prime Video    int64
Disney+        int64
dtype: object

In [6]:
print(movies.shape)
print(movies.dtypes)

(16744, 10)
Title               object
Year                 int64
Age                 object
IMDb               float64
Rotten Tomatoes    float64
Directors           object
Genres              object
Country             object
Language            object
Runtime            float64
dtype: object

In [8]:
# Check for any missing values in Age

movies['Age'].isnull().sum()

9390

In [9]:
# Replace the missing values in Age column with set value "Others".
movies['Age'][movies['Age'].isna()] = "Others"

/Users/rachid/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [10]:
movies['Age'].isnull().sum()

0

### Checking for any missing values in Directors, Genres, Country, and Language.

In [22]:
movies['Directors'].isnull().sum()

726

In [23]:
movies['Genres'].isnull().sum()

275

In [24]:
movies['Country'].isnull().sum()

435

In [25]:
movies['Language'].isnull().sum()

599

### Replace the missing values in Directors, Generes, Country, and Language.

In [26]:
movies['Directors'][movies['Directors'].isna()] = "Others"

/Users/rachid/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
movies['Genres'][movies['Genres'].isna()] = "Others"

/Users/rachid/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [28]:
movies['Country'][movies['Country'].isna()] = "Others"

/Users/rachid/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [29]:
movies['Language'][movies['Language'].isna()] = "Others"

/Users/rachid/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [30]:
movies['Directors'].isnull().sum()

0

In [31]:
movies['Genres'].isnull().sum()

0

In [32]:
movies['Country'].isnull().sum()

0

In [33]:
movies['Language'].isnull().sum()

0

In [38]:
# Determine the data type first.
print(movies.dtypes)

Title               object
Year                 int64
Age                 object
IMDb               float64
Rotten Tomatoes    float64
Directors           object
Genres              object
Country             object
Language            object
Runtime            float64
dtype: object

In [39]:
movies['Rotten Tomatoes'].isnull().sum()

11586

In [40]:
movies['IMDb'].isnull().sum()

571

In [43]:
movies['Rotten Tomatoes'].fillna(movies['Rotten Tomatoes'].mean(),inplace=True)
movies['IMDb'].fillna(movies['IMDb'].mean(),inplace=True)

In [42]:
movies['Rotten Tomatoes'].isnull().sum()

0

In [44]:
movies['IMDb'].isnull().sum()

0